### ISSUE TITLE
Implement PSR-3 interface for Drupal watchdog

### ISSUE THREAD

**Issue by andytruong** [v3kwip/at.module#26]
Please provide new service:

- Service name: 'watchdog'.
- Class: Drupal\at\Watchog (implements Psr\Log\LoggerInterface)
- The service should be accessible via: at()->watchdog().

### Define my service

```yaml
# @file my_module.services.yml
services:
  my_service:
    class: MyService
    arguments: ['@watchdog']
```

### Implement my service

```php
class MyService {
  public function __construct(LoggerInterface $logger) {
    $this->logger = $logger;
  }

  public function getLogger() {
    return $this->logger;
  }

  public function myLogic() {
    $foo = 'bar';
    $this->getLogger()->debug($foo);
  }
}
```

### More

1. Test cases
2. Documentation
